customhost = "employee.cmuwhb8jfzkq.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chuamengsin-employee"
customregion = "us-east-1"
